-- Run once in Supabase SQL Editor for a fresh portfolio database.
create table if not exists public.portfolio_content (
  id bigint primary key,
  content jsonb not null,
  updated_at timestamptz not null default now()
);

insert into public.portfolio_content (id, content)
values (1, '{"profile":{"name":"Lokesh Warke","role":"Full-Stack Developer","tagline":"I build products from pixel → API → database → deployment.","email":"lokeshwarke6@gmail.com","github":"https://github.com/yourusername","linkedin":"https://linkedin.com/in/yourusername","location":"Pune / India","photoUrl":"","philosophy":"I do not want to be defined by one framework. I want to understand the whole product — interface, systems, data, infrastructure and the decisions connecting them."},"skills":{"Frontend":["React","Next.js","TypeScript","JavaScript","Tailwind CSS","HTML/CSS"],"Backend":["Java","Spring Boot","Python","FastAPI","Node.js","REST APIs"],"Data":["PostgreSQL","MySQL","MongoDB","Redis"],"Cloud":["Docker","AWS","Linux","Git","CI/CD"],"AI":["RAG","LLM APIs","LangChain","Vector Search"]},"learning":{"title":"Amazon AWS re/Start","status":"CURRENTLY UPSKILLING","description":"Currently building cloud and IT fundamentals through the Amazon AWS re/Start training batch, with a focus on Linux, networking, AWS Cloud, security, and troubleshooting.","topics":["Linux fundamentals","Networking & troubleshooting","AWS Cloud fundamentals","Cloud security basics","Command line & system administration"],"imageUrl":""},"projects":[{"slug":"opsdesk","name":"OpsDesk","type":"MULTI-TENANT SAAS / HELPDESK","description":"A multi-tenant SaaS helpdesk platform concept for teams to organize support requests, manage tickets, and control access by organization and role.","stack":["Next.js","TypeScript","Spring Boot","Spring Security","JWT","PostgreSQL","Flyway","Docker"],"status":"IN DEVELOPMENT","imageUrl":"","repositoryUrl":"","liveUrl":""},{"slug":"opspilot","name":"OpsPilot","type":"OPERATIONS / AUTOMATION API","description":"An operations-focused application with task-management API endpoints and a backend designed around clear service boundaries and reliable data handling.","stack":["FastAPI","Python","PostgreSQL","Redis","Docker"],"status":"IN DEVELOPMENT","imageUrl":"","repositoryUrl":"","liveUrl":""},{"slug":"documind","name":"DocuMind","type":"AI / DOCUMENT INTELLIGENCE","description":"A document-intelligence project exploring retrieval-augmented generation (RAG) to help users ask questions about information contained in their documents.","stack":["React","RAG","LLM APIs","Embeddings","Vector Search","PostgreSQL"],"status":"IN DEVELOPMENT","imageUrl":"","repositoryUrl":"","liveUrl":""},{"slug":"devtrack","name":"DevTrack","type":"FULL-STACK PLATFORM","description":"A developer productivity and project-management platform concept focused on organizing work through a web interface, backend APIs, and persistent data.","stack":["React","Java","Spring Boot","PostgreSQL","Docker"],"status":"CONCEPT / IN DEVELOPMENT","imageUrl":"","repositoryUrl":"","liveUrl":""}]}'::jsonb)
on conflict (id) do nothing;

-- The Next.js server uses the Supabase service-role key. Keep that key secret.
