import Navbar from '@/components/Navbar';
import ProjectCard from '@/components/ProjectCard';
import Terminal from '@/components/Terminal';
import { ArrowDown, ArrowUpRight, FileDown, Github, Linkedin, ShieldCheck, Wrench, Activity, Cloud, Code2 } from 'lucide-react';
import { getPortfolioContent } from '@/lib/content';
export const dynamic='force-dynamic';
export default async function Home(){
  const {profile,skills,projects,learning}=await getPortfolioContent();
  const notes=[
    {title:'Authentication & authorization',tag:'SPRING SECURITY / JWT',text:'Document the token flow, public versus protected routes, role checks, and how authorization failures are investigated. Add verified request/response examples as implementation evolves.'},
    {title:'Database configuration',tag:'POSTGRESQL / MIGRATIONS',text:'Explain environment-based database configuration, credential troubleshooting, schema migrations, and the checks used to validate connectivity.'},
    {title:'API reliability',tag:'REST / DEBUGGING',text:'Show how request validation, missing request bodies, API error responses, and entity serialization issues are diagnosed and tested.'}
  ];
  return <main id="top"><Navbar/>
    <section className="grid-bg flex min-h-screen items-center pt-24"><div className="mx-auto w-full max-w-7xl px-5 py-24"><div className="mb-8 flex items-center gap-3 mono text-[10px] uppercase tracking-[.3em] text-neutral-500"><span className="h-2 w-2 animate-pulse rounded-full bg-[var(--accent)]"/> developer portfolio · {profile.location}</div><div className="flex items-start justify-between gap-8"><div className="min-w-0 flex-1"><h1 className="max-w-5xl text-[clamp(4rem,12vw,10rem)] font-semibold leading-[.8] tracking-[-.07em]">{profile.name.split(' ').slice(0,-1).join(' ')}<br/><span className="text-neutral-600">{profile.name.split(' ').slice(-1)}</span></h1><div className="mt-12 flex max-w-3xl flex-col justify-between gap-8 md:flex-row md:items-end"><div><p className="mb-2 mono text-xs tracking-[.25em] accent">{profile.role.toUpperCase()}</p><p className="max-w-xl text-xl leading-8 text-neutral-400">{profile.tagline}</p><div className="mt-6 flex flex-wrap gap-3"><a href="#work" className="flex w-fit items-center gap-2 bg-[var(--accent)] px-5 py-3 text-xs font-semibold uppercase tracking-widest text-black">View projects <ArrowDown size={14}/></a><a href="/resume" className="flex w-fit items-center gap-2 border border-neutral-700 px-5 py-3 text-xs uppercase tracking-widest hover:border-white"><FileDown size={14}/> Download resume</a></div></div></div><div className="mt-2 flex gap-4 md:mt-0">{profile.photoUrl ? <img src={profile.photoUrl} alt={profile.name} className="hidden h-36 w-36 rounded-full border border-line object-cover md:block lg:h-48 lg:w-48" /> : <div className="hidden h-36 w-36 items-center justify-center rounded-full border border-line mono text-xs text-neutral-700 md:flex lg:h-48 lg:w-48">PROFILE PHOTO</div>}</div></div></div><div className="mt-16 grid max-w-4xl gap-3 sm:grid-cols-3"><div className="border border-line bg-black/50 p-4"><Code2 className="mb-3 accent" size={18}/><p className="text-sm">Full-stack product development</p></div><div className="border border-line bg-black/50 p-4"><Cloud className="mb-3 accent" size={18}/><p className="text-sm">Cloud learning · AWS re/Start</p></div><div className="border border-line bg-black/50 p-4"><Wrench className="mb-3 accent" size={18}/><p className="text-sm">API debugging & problem solving</p></div></div></div></section>
    <section className="border-t border-line py-24"><div className="mx-auto grid max-w-7xl gap-12 px-5 md:grid-cols-3"><div className="mono text-xs uppercase tracking-[.25em] text-neutral-500">01 / philosophy</div><div className="md:col-span-2"><p className="text-3xl leading-relaxed tracking-tight md:text-5xl">{profile.philosophy}</p></div></div></section>
    <section id="work" className="border-t border-line py-24"><div className="mx-auto max-w-7xl px-5"><div className="mb-12 flex items-end justify-between"><div><div className="mono mb-3 text-xs tracking-[.25em] text-neutral-500">02 / selected work</div><h2 className="text-5xl tracking-tight">Projects & case studies</h2><p className="mt-4 max-w-2xl text-sm leading-6 text-neutral-500">Explore the problem, approach, architecture, technology choices, and deployment roadmap for each project. Live links will appear when projects are actually deployed.</p></div><span className="mono text-xs text-neutral-600">{projects.length.toString().padStart(2,'0')} projects</span></div><div className="grid gap-4 md:grid-cols-2">{projects.map(p=><ProjectCard key={p.slug} p={p}/>)}</div></div></section>
    <section id="learning" className="border-t border-line py-24"><div className="mx-auto grid max-w-7xl gap-10 px-5 md:grid-cols-3"><div className="mono text-xs uppercase tracking-[.25em] text-neutral-500">03 / current upskilling</div><div className="md:col-span-2">{learning.imageUrl ? <img src={learning.imageUrl} alt="AWS re/Start learning" className="mb-8 max-h-64 w-full border border-line object-cover" /> : null}<div className="mb-4 inline-flex items-center gap-2 border border-[var(--accent)]/30 px-3 py-2 mono text-[10px] tracking-widest accent"><span className="h-2 w-2 animate-pulse rounded-full bg-[var(--accent)]"/>{learning.status}</div><h2 className="text-4xl tracking-tight md:text-5xl">{learning.title}</h2><p className="mt-5 max-w-3xl text-lg leading-8 text-neutral-400">{learning.description}</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{learning.topics.map((topic:string)=><div key={topic} className="border border-line bg-[#080808] p-4 text-sm text-neutral-300"><span className="mr-3 accent">↗</span>{topic}</div>)}</div><p className="mt-5 text-xs leading-6 text-neutral-600">Training in progress. Update completed labs and learning topics from <span className="mono text-neutral-400">/admin</span>; only list certifications and labs after completing them.</p></div></div></section>
    <section id="stack" className="border-t border-line py-24"><div className="mx-auto max-w-7xl px-5"><div className="mono mb-4 text-xs tracking-[.25em] text-neutral-500">04 / developer dna</div><h2 className="mb-12 text-4xl tracking-tight">Tools & technologies</h2><div className="grid gap-px border border-line bg-line md:grid-cols-5">{Object.entries(skills).map(([k,v])=><div key={k} className="bg-[#050505] p-6"><h3 className="mb-7 text-sm uppercase tracking-widest">{k}</h3>{v.map(x=><div key={x} className="mb-3 flex items-center gap-2 text-sm text-neutral-500"><span className="h-1 w-1 bg-[var(--accent)]"/>{x}</div>)}</div>)}</div></div></section>
    <section id="engineering-notes" className="border-t border-line py-24"><div className="mx-auto max-w-7xl px-5"><div className="mono mb-3 text-xs tracking-[.25em] text-neutral-500">05 / engineering notes</div><h2 className="text-4xl tracking-tight">How I approach troubleshooting</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-neutral-500">Use these case-study prompts to document real issues, root causes, fixes, and verification steps as work progresses. Replace this guidance with verified details before presenting it as completed experience.</p><div className="mt-10 grid gap-4 md:grid-cols-3">{notes.map((n)=><article key={n.title} className="border border-line bg-[#080808] p-6"><Wrench size={18} className="mb-6 accent"/><div className="mono text-[10px] tracking-widest text-neutral-600">{n.tag}</div><h3 className="mt-3 text-xl">{n.title}</h3><p className="mt-4 text-sm leading-7 text-neutral-500">{n.text}</p></article>)}</div></div></section>
    <section id="journey" className="border-t border-line py-24"><div className="mx-auto grid max-w-7xl gap-12 px-5 md:grid-cols-3"><div className="mono text-xs tracking-[.25em] text-neutral-500">06 / journey</div><div className="md:col-span-2"><div className="border-l border-line pl-6"><div className="mb-12"><div className="mono text-xs text-neutral-600">01 — FOUNDATION</div><h3 className="mt-2 text-2xl">Computer Engineering</h3><p className="mt-2 text-sm leading-6 text-neutral-500">Building the fundamentals of programming, systems, networking and software engineering.</p></div><div className="mb-12"><div className="mono text-xs text-neutral-600">02 — BUILDING</div><h3 className="mt-2 text-2xl">Android → Web → Full Stack</h3><p className="mt-2 text-sm leading-6 text-neutral-500">Moving from application development into modern web applications, APIs and databases.</p></div><div><div className="mono text-xs text-neutral-600">03 — NEXT</div><h3 className="mt-2 text-2xl">Cloud + scalable systems</h3><p className="mt-2 text-sm leading-6 text-neutral-500">Deepening Java, Spring Boot, cloud, DevOps and production engineering skills.</p></div></div></div></div></section>
    <section id="deployment" className="border-t border-line py-24"><div className="mx-auto max-w-7xl px-5"><div className="mono mb-3 text-xs tracking-[.25em] text-neutral-500">07 / deployment roadmap</div><h2 className="text-4xl tracking-tight">Built with production in mind</h2><p className="mt-4 max-w-3xl text-sm leading-7 text-neutral-500">Projects are not advertised as live until they have a real working public URL. Planned deployment work includes environment-based secrets, HTTPS, health checks, logs, database backups, and basic security review.</p><div className="mt-8 grid gap-4 sm:grid-cols-3"><div className="border border-line p-5"><Activity className="mb-4 accent" size={20}/><h3 className="font-medium">Real status only</h3><p className="mt-2 text-sm leading-6 text-neutral-500">No fake uptime badges or fabricated usage metrics.</p></div><div className="border border-line p-5"><ShieldCheck className="mb-4 accent" size={20}/><h3 className="font-medium">Security & reliability</h3><p className="mt-2 text-sm leading-6 text-neutral-500">Document auth, input validation, secret handling, and database access controls.</p></div><div className="border border-line p-5"><Cloud className="mb-4 accent" size={20}/><h3 className="font-medium">Cloud-ready path</h3><p className="mt-2 text-sm leading-6 text-neutral-500">Plan frontend, API, and managed database hosting before adding real demo links.</p></div></div></div></section>
    <Terminal/>
    <section id="resume" className="border-t border-line py-20"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-6 px-5 md:flex-row md:items-center"><div><div className="mono mb-3 text-xs tracking-[.25em] text-neutral-500">08 / recruiter-ready profile</div><h2 className="text-3xl tracking-tight">Resume, generated from current portfolio data</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-neutral-500">The resume page uses the latest saved profile, skills, learning details and projects. Update your portfolio in /admin, then download the refreshed resume.</p></div><a href="/resume" className="flex w-fit items-center gap-3 border border-[var(--accent)] px-5 py-4 text-xs uppercase tracking-widest hover:bg-[var(--accent)] hover:text-black"><FileDown size={16}/> View / download resume</a></div></section>
    <section id="contact" className="border-t border-line py-24"><div className="mx-auto max-w-7xl px-5"><div className="mono mb-5 text-xs tracking-[.25em] text-neutral-500">09 / contact</div><div className="flex flex-col justify-between gap-10 md:flex-row md:items-end"><div><h2 className="max-w-3xl text-5xl leading-tight md:text-7xl">Have a problem worth building?</h2><p className="mt-6 text-neutral-500">For content updates, open <span className="mono text-neutral-300">/admin</span>.</p></div><div className="flex flex-col gap-4"><a href={profile.github} target="_blank" rel="noreferrer" className="flex items-center gap-3 text-sm hover:accent"><Github size={16}/> GitHub <ArrowUpRight size={15}/></a><a href={profile.linkedin} target="_blank" rel="noreferrer" className="flex items-center gap-3 text-sm"><Linkedin size={16}/> LinkedIn <ArrowUpRight size={15}/></a><a href={`mailto:${profile.email}`} className="flex items-center gap-3 text-sm">{profile.email} <ArrowUpRight size={15}/></a></div></div></div></section>
    <footer className="border-t border-line py-8"><div className="mx-auto flex max-w-7xl justify-between px-5 mono text-[10px] uppercase tracking-widest text-neutral-600"><span>{profile.name.toUpperCase().replace(/\s+/g,'-')}.SYS</span><span>Built with Next.js · <a href="/admin" className="hover:text-white">Edit content</a></span></div></footer>
  </main>
}
